site_name: KubeCraft
repo_url: https://github.com/mischavandenburg/kubecraft
repo_name: KubeCraft

theme:
  name: material
  logo: ./assets/img/kubecraft-logo-small.jpg
  icon:
    repo: material/github
    edit: material/pencil
    view: material/eye
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mischavandenburg/kubecraft
    - icon: material/school
      link: https://skool.com/kubecraft
